### ISSUE TITLE
deamidation of lock-mass peptide

### ISSUE THREAD

**Issue by lschaffer2** [stefanks/MyTools#2]
Hi Stefan, in my last round of MS runs, the lock mass peptide has a more intense peak at 590.22 instead of 589.23 because of deamidation. It would be great if the rawlockmass software could look for both of those peaks and choose the most intense one to calibrate.

**Comment by stefanks** [comment]
Try now

**Comment by lschaffer2** [comment]
It throws an exception at line 50 and says the sequence contains no elements... initializing monoisotopicPeak to null, then adding a try around when setting it to the peak w/ highest Y seems to work fine. 

Also, I noticed there isn't the code for looking for the other monoisotopic peaks/the sumErrors variable. Did you find that that doesn't work well or would it be too complicated to also have that when looking for deamidated peaks in addition to the unmodified peaks?

**Comment by stefanks** [comment]
Yea, I found it doesn't add much, and makes the code more complicated. 
Could you submit a pull request with your change?

Thanks!
